<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Version>0.11.0-preview.1</Version>
    <AssemblyVersion>0.11.0.0</AssemblyVersion>
    <FileVersion>0.11.0.0</FileVersion>
    <Deterministic>true</Deterministic>
    <PathMap>$(MSBuildProjectDirectory)=/_/$(MSBuildProjectName)</PathMap>

    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable><ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Localizer.Core/Localizer.Core.csproj" />
    <ProjectReference Include="../Localizer.Translation/Localizer.Translation.csproj" />
    <ProjectReference Include="../Localizer.Jellyfin/Localizer.Jellyfin.csproj" />
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Jellyfin.Common" Version="12.0.0" ExcludeAssets="runtime" PrivateAssets="all" />
    <PackageReference Include="Jellyfin.Controller" Version="12.0.0" ExcludeAssets="runtime" PrivateAssets="all" />
    <PackageReference Include="Jellyfin.Model" Version="12.0.0" ExcludeAssets="runtime" PrivateAssets="all" />
    <PackageReference Include="Jellyfin.Data" Version="12.0.0" ExcludeAssets="runtime" PrivateAssets="all" />
    <PackageReference Include="Jellyfin.Database.Implementations" Version="12.0.0" ExcludeAssets="runtime" PrivateAssets="all" />
    <EmbeddedResource Include="Web/admin.html" />
    <EmbeddedResource Include="Web/menu.zh-Hans.json" WithCulture="false" LogicalName="Localizer.Plugin.Web.menu.zh-Hans.json" />
    <EmbeddedResource Include="../../resources/title-rules.zh-Hans.json" LogicalName="Localizer.Rules.zh-Hans.json" />
    <EmbeddedResource Include="../../resources/title-rules.en.json" LogicalName="Localizer.Rules.en.json" />
  </ItemGroup>
</Project>
